# Generated by Django 5.0 on 2023-12-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
