# Generated by Django 5.0 on 2023-12-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
